### ISSUE TITLE
PM> install-package Microsoft.AspNet.WebApi.Client

### ISSUE THREAD

**Issue by perragradeen** [LiljebergXYZ/SwedbankSharp#3]
To get it to build. You must do:
PM> install-package Microsoft.AspNet.WebApi.Client

**Comment by LiljebergXYZ** [comment]
You're absolutely right, I haven't ran the project in a while. I'll be updating the dependencies.

**Comment by perragradeen** [comment]
:). Tack för en bra wrapper btw.

**Comment by LiljebergXYZ** [comment]
Tackar för komplimangen. Det var ett rätt så kul dagsprojekt :)
Ska vara löst nu med.
